import requests
from bs4 import BeautifulSoup


res = requests.get('https://www.indiatoday.in/top-stories')
soup = BeautifulSoup(res.text, "lxml")

news_box = soup.find('div', {'class' : "view-content"})
all_news = news_box.find_all('a')

for news in all_news:
	print(news.text)
	print()
    
#     <div class="view-content"><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/847340-aaditya-thackeray-uddha-170x96.jpeg?lF8MOG7ItEi0oKx3r0_8GomjUDbTXZ5P" alt="Uddhav Thackeray, Aaditya Thackeray, Shiv Sena, Maharashtra polls" title="Uddhav Thackeray, Aaditya Thackeray, Shiv Sena, Maharashtra polls"></div><div class="detail"><h2 class="" title="Maharashtra elections: Too early for Aaditya to get CM post, says Shiv Sena chief Uddhav Thackeray"><a href="/elections/maharashtra-assembly-election/story/maharashtra-elections-too-early-for-aaditya-to-get-cm-post-says-shiv-sena-chief-uddhav-thackeray-1606815-2019-10-07">Too early for Aaditya to get CM post, says Uddhav Thackeray</a></h2><p>While Shiv Sena chief Uddhav Thackeray has stressed on keeping his vow to his
# father -- that a Shiv Sainik will one day become Maharastra CM, he does not
# seem to be in a hurry to fulfil the promise through son Aaditya Thackeray.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/war_1-170x96.png?a7DdWSjVzWlLAeYDzqirS0p1giBfBfXB" alt="War box office collection" title="War box office collection"></div><div class="detail"><h2 class="" title="War box office collection: Day 5"><a href="/movies/bollywood/story/war-box-office-collection-day-5-1606807-2019-10-07">War box office collection: Day 5</a></h2><p>Starring Hrithik Roshan and Tiger Shroff in the lead roles, War is now
# inching towards the Rs 200-crore club.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/AP19279539998344-170x96.jpeg?dUMcwVvMsMGNhD6QNdTEV1mqnSvQYpOI" alt="Wolverhampton Wanderers' Adama Traore scored 2 goals (AP Photo)" title="We were not organised: Pep Guardiola after Manchester City's shock loss to Wolverhampton"></div><div class="detail"><h2 class="" title="We were not organised: Pep Guardiola after Manchester City's shock loss to Wolverhampton"><a href="/sports/football/story/manchester-city-vs-wolverhampton-wanderers-premier-league-pep-guardiola-reaction-1606813-2019-10-07">It was not our best day: Guardiola dejected after City lose to Wolverhampton</a></h2><p>Manchester City went down 2-0 vs Wolverhampton with Adama Traore scoring a
# late double at a stunned Etihad Stadium.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/HongKong-170x96.png?UESsyZ7Gbb._1WQ6ISW6K4H8kwe_rc3G" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="Hong Kong metro partially reopens, city struggles after violent weekend"><a href="/world/story/hong-kong-violence-metro-reopens-1606812-2019-10-07">Hong Kong metro partially reopens, city struggles after violent weekend</a></h2><p>Scores of protesters were arrested and bussed away under the new emergency
# laws, which came into effect on Friday night, after some of the most violent
# clashes in four months of protests virtually shut the city down on Saturday.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/Sukhbir-170x96.png?p0x_2SKxlPQNw30nkc.RArBem2kxMFbZ" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="Taran Taran blast accused hatched plan to kill Sukhbir Singh Badal, reveals probe"><a href="/india/story/tarn-taran-blast-sukhbir-badal-target-conspiracy-amritsar-punjab-1606811-2019-10-07">Taran Taran blast accused hatched plan to kill Sukhbir Singh Badal, reveals probe</a></h2><p>The terror module behind the Tarn Taran blasts had allegedly planned another
# attack in November 2016. Former Punjab Deputy CM Sukhbir Singh Badal was to
# be the target, a probe has revealed.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/2019-10-06T171553Z_1206273962_-170x96.png?Fe8kZeo7wwNH57DDIU8Kj2jk6EX5Z14B" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="We have given ourselves a big uphill task to get in top-4: Solskjaer after Manchester United defeat"><a href="/sports/football/story/manchester-united-manager-ole-gunnar-solskjaer-reaction-after-newcastle-united-loss-1606810-2019-10-07">We need to get the confidence back: Ole Solskjaer after ManU lose to Newcastle</a></h2><p>A Manchester United line-up missing the likes of Anthony Martial, Paul Pogba
# and Jesse Lingard looked powder-puff against a defence that leaked five goals
# last week against Leicester City.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/HSBC-170x96.png?C1rHMXL6Y2aHCG4TBYQHJgKR9d8Tatbf" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="HSBC to cut up to 10,000 high-paid jobs in drive to slash costs: Report"><a href="/world/story/hsbc-to-cut-up-to-10-000-high-paid-jobs-in-drive-to-slash-costs-report-1606809-2019-10-07">HSBC to cut up to 10,000 high-paid jobs in drive to slash costs: Report</a></h2><p>HSBC could announce the beginning of the latest cost-cutting drive and job
# cuts when it reports third-quarter results later this month.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/AP19279754014802-170x96.jpeg?ez_05gN1DvydOlKathQQoqHui7ZmRuXz" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="La Liga: Ruthless Barcelona thrash Sevilla but have two players sent off"><a href="/sports/football/story/la-liga-ruthless-barcelona-thrash-sevilla-but-have-two-players-sent-off-1606808-2019-10-07">La Liga: Messi, Suarez lead 9-man Barcelona to 4-0 win over Sevilla</a></h2><p>The victory saw Barcelona leapfrog Atletico Madrid into second place on 16
# points, two behind leaders Real Madrid who they meet in three weeks' time at
# the Camp Nou.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/jemimah7102019_0-170x96.png?k2sLI0cHPCZQSj7wI11INcZMNAD.imbB" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="Watch: Jemimah Rodrigues and Harleen Deol rap special song for Harmanpreet Kaur"><a href="/sports/cricket/story/jemimah-rodrigues-harleen-deol-rap-song-tribute-for-harmanpreet-kaur-100th-t20i-match-1606806-2019-10-07">Jemimah Rodrigues, Harleen Deol pay special tribute to Harmanpreet 'Thor'</a></h2><p>Harmanpreet Kaur recently became the most-capped player for India in T20
# international cricket when she played her 100th match against South Africa.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/RTX769A5-170x96.jpeg?qQzYMf4UfJ36i7j5Spec5RKqCzw4U1ht" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="Iraqi police fire on protesters in new unrest, death toll passes 100"><a href="/world/story/iraqi-police-fire-on-protesters-in-new-unrest-death-toll-passes-100-1606805-2019-10-07">Iraqi police fire on protesters in new unrest, death toll passes 100</a></h2><p>The unrest in Iraq is the biggest security and political challenge for Prime
# Minister Adel Abdul Mahdi's government since it took power a year ago. The
# clashes have revived fears of a new spiral of violence that could suck in
# influential militia groups and be exploited by Islamic State.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/gyanchand_parakh-170x96.jpeg?hxWvB0nr3wEr3_9V3f_hxIda9AvZkzIx" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="Ram Mandir to be built by November 17, claims Rajasthan BJP MLA"><a href="/india/story/ram-mandir-to-be-built-by-november-17-claims-rajasthan-bjp-mla-1606804-2019-10-07">Ram Mandir to be built by November 17, claims Rajasthan BJP MLA</a></h2><p>BJP MLA from Pali, Rajasthan Gyanchand Parakh has declared that the Ram
# Mandir will be built in Ayodhya before November 17 -- the day Supreme Court
# will announce its verdict in the matter.</p></div></div><div class="catagory-listing"><div class="pic "> <img src="https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/gul_panag-170x96.png?nTBS7DMlp2XFPpEvNX4Q7PNma7CuCuWi" class="lazyloaded" width="170" height="96"></div><div class="detail"><h2 class="" title="#20yearchallenge: Gul Panag sports 1999 swimsuit on Maldives vacay. Internet says we are impressed"><a href="/movies/celebrities/story/gul-panag-sports-1999-swimsuit-on-maldives-vacay-1606803-2019-10-07"> #20yearchallenge: Gul Panag sports 1999 swimsuit on Maldives vacay</a></h2><p>Gul Panag took to Instagram to share a collage of her two photos from her
# Maldives vacation, one from 1999 and another from 2019.</p></div></div></div><h2 class="element-invisible">Pages</h2><div class="item-list"><ul class="pager"><li class="pager-current first">1</li><li class="pager-item"><a title="Go to page 2" href="/top-stories?page=1">2</a></li><li class="pager-item"><a title="Go to page 3" href="/top-stories?page=2">3</a></li><li class="pager-item"><a title="Go to page 4" href="/top-stories?page=3">4</a></li><li class="pager-item"><a title="Go to page 5" href="/top-stories?page=4">5</a></li><li class="pager-item"><a title="Go to page 6" href="/top-stories?page=5">6</a></li><li class="pager-item"><a title="Go to page 7" href="/top-stories?page=6">7</a></li><li class="pager-item"><a title="Go to page 8" href="/top-stories?page=7">8</a></li><li class="pager-item"><a title="Go to page 9" href="/top-stories?page=8">9</a></li><li class="pager-ellipsis">…</li><li class="pager-next"><a title="Go to next page" href="/top-stories?page=1">Next</a></li><li class="pager-last last"><a title="Go to last page" href="/top-stories?page=14">last »</a></li></ul></div>